development:
  adapter: postgresql
  database: destinations_db
  host: localhost
  pool: 5
  timeout: 5000

production:
  url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: destinations_db
  host: localhost
  pool: 5
  timeout: 5000
