development:
  adapter: postgresql
  database: db/locations1
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: db/locations2
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: db/locations3
  pool: 5
timeout: 5000
